#!/bin/bash

pgrep -x sxhkd >/dev/null || sxhkd &

"$HOME"/.config/polybar/launch.sh

if [[ $(xrandr -q | grep 'DP-1 connected') ]]; then
    xrandr --output DP-1 --mode 1920x1080 --rate 60 --rotate normal --left-of HDMI-0

    bspc monitor DP-1 -d 1 2
    bspc monitor HDMI-0 -d 3 4
else
    bspc monitor -d 1 2 3 4
fi

xrandr --output HDMI-0 --mode 1920x1080 --rate 75 --rotate normal --primary

bspc config border_width 2
bspc config window_gap 6
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config automatic_scheme spiral

bspc rule -a Chromium desktop='^2'
